# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: v2022.0.1
author: <a href="https://www.camsys.com">Cambridge Systematics</a> for the <a href="https://activitysim.github.io/">ActivitySim
  Consortium</a>
logo: logo.png
copyright: 2022 AMPO Research Foundation    # Copyright year to be placed in the footer

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/camsys/sharrow  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  extra_navbar: ''  # Will be displayed underneath the left navbar.
  home_page_in_navbar: true  # Whether to include your home page in the left Navigation Bar
  search_bar_text: Search these docs...

sphinx:
  extra_extensions:
  - sphinx.ext.autodoc
  - sphinx.ext.napoleon
  - sphinx.ext.viewcode
  config:
    add_module_names: false
    html_theme_options:
      home_page_in_toc: true
      search_bar_text: Search these docs...
      repository_url: https://github.com/ActivitySim/sharrow
      use_repository_button: true
      use_issues_button: true
      repository_branch: master
      path_to_docs: docs
      extra_navbar:
