name: deploy-book

# Only run this when the main branch changes and is tagged with a version tag.
on:
  push:
    branches:
    - main
    tags:
    - v[0-9]+.[0-9]+**

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: Mambaforge
        miniforge-version: latest
        use-mamba: true
        environment-file: envs/testing.yml
        python-version: ${{ matrix.python-version }}
        activate-environment: testing-env
        auto-activate-base: false
        auto-update-conda: false
    - name: Install Jupyterbook
      run: |
        mamba install jupyter-book -c conda-forge
    - name: Install sharrow
      run: |
        python -m pip install --no-deps -e .
    - name: Conda checkup
      run: |
        conda info -a
        conda list
    - name: Build the docs
      run: |
        jupyter-book build ./docs
    - name: Push to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3.5.9
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Token is created automatically by Github Actions, no other config needed
        publish_dir: ./docs/_build/html
